---
- name: "Copy backend artifact"
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Extract artifact.tar.gz into /home/ubuntu
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .

- name: Executing node
  become: yes
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- start
    pm2 ls
