---
- name: "Install dependencies"
  apt:
    name: ["nodejs", "npm", "tar"]
    state: latest
    update_cache: yes

- name: "Copy backend artifact"
  copy:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu

- name: Extract artifact.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- start
    pm2 ls
