---
- name: "Create app directory"
  file:
    path: /home/ubuntu/udapeople
    state: directory

- name: "Copy backend artifact"
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/udapeople/artifact.tar.gz
    backup: yes

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 3

- name: Extract artifact.tar.gz into /home/ubuntu/udapeople
  shell: |
    cd /home/ubuntu/udapeople
    tar xvzf artifact.tar.gz -C .

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 3

- name: Executing node
  shell: |
    cd /home/ubuntu/udapeople
    NODE_PORT=3030 pm2 start npm --name 'udapeople' -- start
    pm2 ls
